// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7DloUgaV_rRUmG5pBcBb8WqWYQeX_k4',
    appId: '1:8464881413:web:a99f9cbc2fe1dabbf3496c',
    messagingSenderId: '8464881413',
    projectId: 'kaksekai-ff46d',
    authDomain: 'kaksekai-ff46d.firebaseapp.com',
    storageBucket: 'kaksekai-ff46d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiY_EdHVj1cvwr45e9fyuKigan_bMalL8',
    appId: '1:8464881413:android:30d44a6a0886f9b5f3496c',
    messagingSenderId: '8464881413',
    projectId: 'kaksekai-ff46d',
    storageBucket: 'kaksekai-ff46d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWsSYKn1drGm8oo5IfAVz3kFVhAtmSWYo',
    appId: '1:8464881413:ios:4ad48588cf79790ff3496c',
    messagingSenderId: '8464881413',
    projectId: 'kaksekai-ff46d',
    storageBucket: 'kaksekai-ff46d.firebasestorage.app',
    iosClientId: '8464881413-dk0ipjl0kgrsoak5fmgb2riko1g851kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaksekaiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWsSYKn1drGm8oo5IfAVz3kFVhAtmSWYo',
    appId: '1:8464881413:ios:4ad48588cf79790ff3496c',
    messagingSenderId: '8464881413',
    projectId: 'kaksekai-ff46d',
    storageBucket: 'kaksekai-ff46d.firebasestorage.app',
    iosClientId: '8464881413-dk0ipjl0kgrsoak5fmgb2riko1g851kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaksekaiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC7DloUgaV_rRUmG5pBcBb8WqWYQeX_k4',
    appId: '1:8464881413:web:3d981a1619d79b54f3496c',
    messagingSenderId: '8464881413',
    projectId: 'kaksekai-ff46d',
    authDomain: 'kaksekai-ff46d.firebaseapp.com',
    storageBucket: 'kaksekai-ff46d.firebasestorage.app',
  );
}
